import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { createClient } from "@/lib/supabase/server";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  let selectedDetail: any = null;
  if (user) {
    const { data } = await supabase.rpc(
      "rpc_get_expediente_seleccionado_detail"
    );
    selectedDetail = data;
  }
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Global selected expediente badge visible to all users */}
        <div className="w-full border-b bg-muted/30">
          <div className="container mx-auto py-1.5 px-4">
            <div className="text-[11px] md:text-xs inline-flex items-center gap-2 rounded px-2 py-0.5">
              <span className="text-muted-foreground">Expediente seleccionado:</span>
              <span className="font-medium">{selectedDetail?.expediente_codigo ?? "—"}</span>
              {selectedDetail?.nombre ? (
                <span className="text-muted-foreground">— {selectedDetail?.nombre}</span>
              ) : null}
            </div>
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
